name: Build & Deploy Storybook
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: git config
        with:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
      - name: Install and Build
        run: |
          yarn install
          yarn build
      - name: Deploy Storybook
        with:
          TEST2: ${{ secrets.TOKEN }}
        run: echo $TEST2
