name: Build & Deploy
on:
  push:
    branches:
      - actions_test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
      - name: git config
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
      - name: Build And Push
        run: |
          yarn install
          yarn build
          git add .
          git commit -m 'chore: update bundle file $USER_NAME $USER_EMAIL'
          git push --set-upstream origin actions_test
      - name: Publish storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
