name: Publish storybook
on:
  push:
    branches:
      - master
    paths: ['src/stories/**/*']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - name: Install and Build Storybook
        run: |
          yarn install
          yarn build
          yarn build-storybook
      - name: Publish storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
