import React from 'react';
type TextInputProps = {
    type?: string;
    name?: string;
    label?: string;
    disabled?: boolean;
    placeholder?: string;
    helperMessage?: string;
    errorMessage?: string;
    extraMessage?: string;
    maxLength?: number;
    onChange?: () => void;
    onBlur?: React.FocusEventHandler<HTMLInputElement>;
    onFocus?: React.FocusEventHandler<HTMLInputElement>;
    value?: string;
    verificationTime?: string;
    handleClickOnExtraMessage: () => void;
    flag: boolean;
    [key: string]: any;
};
declare const TextInput: React.FC<TextInputProps>;
export default TextInput;
